using System;
using Microsoft.EntityFrameworkCore.Migrations;
#nullable disable

namespace FinTreX.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddPortfolioValueSnapshots : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"PortfolioValueSnapshots\";");

            migrationBuilder.Sql(@"
                CREATE TABLE ""PortfolioValueSnapshots"" (
                    ""Id"" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    ""PortfolioId"" integer NOT NULL,
                    ""CapturedAtUtc"" timestamp with time zone NOT NULL,
                    ""TotalValueTry"" numeric(24,8) NOT NULL,
                    ""TotalValueUsd"" numeric(24,8) NOT NULL,
                    ""UsdTryRate"" numeric(18,6) NULL,
                    CONSTRAINT ""FK_PortfolioValueSnapshots_Portfolios_PortfolioId""
                        FOREIGN KEY (""PortfolioId"") REFERENCES ""Portfolios"" (""Id"") ON DELETE CASCADE
                );
            ");

            migrationBuilder.Sql(@"
                CREATE INDEX ""IX_PortfolioValueSnapshots_PortfolioId_CapturedAtUtc""
                ON ""PortfolioValueSnapshots"" (""PortfolioId"", ""CapturedAtUtc"");
            ");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("DROP TABLE IF EXISTS \"PortfolioValueSnapshots\";");
        }
    }
}
