using FinTreX.Core.Enums;
using System;

namespace FinTreX.Core.Entities
{
    /// <summary>
    /// A consultancy task created by a User and assigned to an Economist.
    /// Has a 1:1 relationship with PreAnalysisReport (generated by AI in Faz 3-4).
    /// </summary>
    public class ConsultancyTask
    {
        public int Id { get; set; }

        /// <summary>The user who created this task.</summary>
        public string UserId { get; set; }

        /// <summary>The economist assigned to analyze this task.</summary>
        public string EconomistId { get; set; }

        public TaskCategory Category { get; set; }

        /// <summary>Short title (e.g. "THYAO Hisse Analizi").</summary>
        public string Title { get; set; }

        /// <summary>Detailed description of what analysis is requested.</summary>
        public string Description { get; set; }

        public TaskPriority Priority { get; set; } = TaskPriority.Medium;

        /// <summary>Optional deadline for the economist to complete the task.</summary>
        public DateTime? Deadline { get; set; }

        public ConsultancyTaskStatus Status { get; set; } = ConsultancyTaskStatus.Pending;

        public DateTime CreatedAtUtc { get; set; } = DateTime.UtcNow;

        /// <summary>When the economist marked this task as completed.</summary>
        public DateTime? CompletedAtUtc { get; set; }

        // ── Navigation — 1:1 AI Report ───────────────────────────────────────
        public PreAnalysisReport PreAnalysisReport { get; set; }
    }
}
