using System;

namespace FinTreX.Core.Entities
{
    /// <summary>
    /// AI-generated pre-analysis report linked 1:1 to a ConsultancyTask.
    /// Generated by the Python CrewAI microservice (Faz 3-4).
    /// Until integration is complete, this will be null/empty for new tasks.
    ///
    /// IMPORTANT: This report provides OBJECTIVE data summarization only.
    /// It MUST NOT contain financial advice (buy/sell recommendations).
    /// </summary>
    public class PreAnalysisReport
    {
        public int Id { get; set; }

        /// <summary>FK to the associated consultancy task (1:1).</summary>
        public int ConsultancyTaskId { get; set; }

        /// <summary>Short summary paragraph of the analysis.</summary>
        public string Summary { get; set; }

        /// <summary>Risk level assessment: "Low", "Medium", "High".</summary>
        public string RiskLevel { get; set; }

        /// <summary>General market outlook commentary.</summary>
        public string MarketOutlook { get; set; }

        /// <summary>Key findings as a JSON array string for structured display.</summary>
        public string KeyFindings { get; set; }

        /// <summary>Full AI output in Markdown or JSON format for detailed view.</summary>
        public string RawContent { get; set; }

        public DateTime GeneratedAtUtc { get; set; } = DateTime.UtcNow;

        /// <summary>Whether the AI successfully generated the report.</summary>
        public bool IsSuccessful { get; set; }

        /// <summary>Error message if generation failed.</summary>
        public string ErrorMessage { get; set; }

        // ── Navigation ───────────────────────────────────────────────────────
        public ConsultancyTask ConsultancyTask { get; set; }
    }
}
